"""
Run this once to generate VAPID keys for Web Push notifications.
    python generate_vapid_keys.py
It creates/updates vapid_config.py with your keys — don't share the private key.
"""
from py_vapid import Vapid
from cryptography.hazmat.primitives import serialization
import base64

v = Vapid()
v.generate_keys()

# pywebpush expects the private key as a base64url-encoded DER (PKCS8) string —
# NOT the PEM format (with -----BEGIN/END----- headers)
der = v.private_key.private_bytes(
    encoding=serialization.Encoding.DER,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption(),
)
private_b64url = base64.urlsafe_b64encode(der).rstrip(b"=").decode()

pub_numbers = v.public_key.public_numbers()
x = pub_numbers.x.to_bytes(32, "big")
y = pub_numbers.y.to_bytes(32, "big")
raw_pub = b"\x04" + x + y
public_b64url = base64.urlsafe_b64encode(raw_pub).rstrip(b"=").decode()

with open("vapid_config.py", "w") as f:
    f.write('# Auto-generated by generate_vapid_keys.py — do not share VAPID_PRIVATE_KEY publicly\n\n')
    f.write(f'VAPID_PRIVATE_KEY_PEM = "{private_b64url}"\n\n')
    f.write(f'VAPID_PUBLIC_KEY = "{public_b64url}"\n\n')
    f.write('VAPID_CLAIM_EMAIL = "mailto:you@example.com"  # change to your email\n')

print("vapid_config.py created.")
print("Public key (frontend will fetch this automatically):", public_b64url)